export const dialogContentClassName = ''
export const dialogHeaderClassName = ''
export const dialogFooterClassName = ''
export const dialogTitleClassName = ''
export const dialogDescriptionClassName = ''
