export const alertDialogContentClassName = ''
export const alertDialogHeaderClassName = ''
export const alertDialogFooterClassName = ''
export const alertDialogTitleClassName = ''
export const alertDialogDescriptionClassName = ''
export const alertDialogActionClassName = ''
export const alertDialogCancelClassName = ''
